version: '3.8'

services:
  relay:
    build: .
    ports:
      - "3334:3334"
    environment:
      - PORT=3334
      - DATABASE_URL=postgres://nark:narkpass@postgres:5432/nark_archival?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nark-network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=nark
      - POSTGRES_PASSWORD=narkpass
      - POSTGRES_DB=nark_archival
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nark-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nark -d nark_archival"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nark-network:
    driver: bridge